### ISSUE TITLE
Synthetic tree models

### ISSUE THREAD

**Issue by drapado** [meyerls/FruitNeRF#3]
Hi,

Great work! 
I was wondering if you plan to publish or make accessible the synthetic tree models.

Cheers!

**Comment by meyerls** [comment]
Unfortunately I won't be able to release the blender scenes due to license regulations. But as I mentioned in the paper, the model were purchased from XFROG: [LIBRARY : FRUIT TREES](https://www.xfrog.com/product-page/library-fruit-trees).

To obtain semantic masks and render the images from a hemisphere would than only require a little bit of effort.
